import { HelpConfig } from "@/components/HelpPanel";

export const HELP: Record<string, HelpConfig> = {

  build: {
    title: "Build Dashboard — Empire Command",
    what: "Your real-time surveillance centre. Every system in the empire visible from one screen.",
    why: "This is your mission control. The Feed tab shows every action Claude Code and Claude Chat take — in real time. Health shows client scores. Brief shows today's AI-generated priorities. DB Tables shows what data exists. Pages lets you navigate everywhere.",
    howTo: [
      { step: "Check the Feed tab first", detail: "See the live bridge feed — every background task, migration, build step, and automation run appears here with timestamps." },
      { step: "Watch the stats bar", detail: "8 numbers at the top update every 15 seconds: projects, learnings, verified tactics, LLM citations, alerts, leads, feed messages, total DB rows." },
      { step: "Use the Health tab", detail: "See all client health scores at a glance. Red = needs attention. Click Recalculate All to refresh all scores." },
      { step: "Generate a brief if empty", detail: "Click the Brief tab. If today's brief hasn't been generated, press Generate to get AI priorities for the day." },
      { step: "Check DB Tables for data flow", detail: "Every table with row counts. If a table shows 0, that feature hasn't been used yet. Green = data flowing." },
    ],
    actions: [
      { label: "📡 Live Feed", desc: "Every bridge message from all automation runs, Claude Code, and Claude Chat. Your audit trail." },
      { label: "❤️ Health", desc: "Client health scores, churn risk indicators, upsell signals. Recalculate with one button." },
      { label: "🌅 Brief", desc: "Today's AI morning brief with priority actions, wins, risks, and opportunities." },
      { label: "🗄 DB Tables", desc: "Live row counts for all 23 database tables. See exactly what data is flowing." },
      { label: "🗺 Pages", desc: "Navigate to any page. Quick action buttons to trigger key automations instantly." },
    ],
    tips: [
      "The feed auto-refreshes every 15 seconds — you don't need to reload.",
      "Bridge messages marked 💬 are from Claude Chat (me). Messages marked ▸ are from Claude Code (automated).",
      "If the stats show 0 learnings, run a task from Launchpad to start the Brain learning.",
      "Health scores below 50 need immediate attention — check the churn signals.",
      "The DB Tables tab is your best indicator of whether the empire is actually working.",
    ],
    faq: [
      { q: "Why is the feed empty?", a: "The bridge table needs messages. Run any automation from Launchpad or trigger calculate_all_health from the Pages tab quick actions." },
      { q: "What does 'status' vs 'thinking' mean in the feed?", a: "'thinking' = a task started. 'status' = task completed with result. 'error' = something failed and needs attention." },
      { q: "Why are DB rows 0 for new tables?", a: "New tables like morning_briefs or client_health start empty. They populate automatically as the daily cron runs, or you can trigger them manually from Pages." },
    ],
  },

  empire: {
    title: "Empire Command — God View",
    what: "One screen to see the entire business: every client, every metric, every alert, today's priorities.",
    why: "Empire Command aggregates data from every corner of the system. Instead of clicking through 15 pages, you see the entire state of your SEO business in one dashboard. The morning brief tells you what matters today. Health scores tell you which clients need attention. Alerts tell you what's urgent.",
    howTo: [
      { step: "Start here every morning", detail: "Open Empire Command first. The headline from today's morning brief tells you the empire's status in one sentence." },
      { step: "Check client health scores", detail: "The left panel shows all projects with health scores (0-100). Red = crisis. Yellow = at risk. Green = healthy." },
      { step: "Read today's priority actions", detail: "The bottom panel shows the 3 most important things to do today, generated by AI based on all available data." },
      { step: "Act on urgent alerts", detail: "Red alert badges in the top right mean something needs immediate attention — click Alerts to see details." },
    ],
    actions: [
      { label: "Empire Stats", desc: "Live counts of projects, learnings, verified tactics, LLM citations, unread alerts, and prospects." },
      { label: "Client Health Overview", desc: "All client health scores with churn risk. Red border = high risk. Dot colour shows risk level." },
      { label: "Unread Alerts", desc: "Latest urgent alerts surfaced from all monitoring systems." },
      { label: "Priority Actions", desc: "Today's 3 highest-impact actions generated by the morning brief AI." },
    ],
    tips: [
      "Click any page link in the top nav to drill down into any area.",
      "If health scores are missing, go to /health and click Recalculate All.",
      "If the brief shows 'Empire operational' without specifics, go to /morning-brief and generate a fresh one.",
      "The empire stats bar updates on every page load — hit Refresh to get the latest.",
    ],
    faq: [
      { q: "What is a 'healthy' empire score?", a: "Projects above 70 are healthy. 50-70 needs attention. Below 50 is concerning. The average across all projects should be above 60." },
      { q: "Why are LLM Citations 0?", a: "LLM visibility checks haven't been run yet. Go to /llm-visibility, select a project, and click Run Check." },
    ],
  },

  intake: {
    title: "Intake — Lead Capture",
    what: "A public-facing page where potential clients get an instant audit of their website. Your automated sales front door.",
    why: "Share the /intake URL with prospects or embed it anywhere. They enter their domain, the system crawls it in 5 seconds, finds SEO issues, scores the lead, and captures their email. You never manually audit a prospect again — it's all automatic.",
    howTo: [
      { step: "Share the intake URL", detail: "Give prospects the URL seoseason.com/intake. Works on mobile, loads instantly, no login needed." },
      { step: "Prospect enters their domain", detail: "The system fetches their site and checks for: missing title tags, missing meta descriptions, missing H1, no structured data. Each found issue increases the lead score." },
      { step: "Issues are shown immediately", detail: "The prospect sees their specific problems — making the value obvious before they even give their email." },
      { step: "Email captured", detail: "Prospect enters email to get the full report. Lead is created in the Prospects database with score and audit data." },
      { step: "Follow up in /empire", detail: "New leads appear in Empire stats under Prospects. Generate a proposal directly from the data captured." },
    ],
    actions: [
      { label: "Instant site audit", desc: "Crawls the prospect's site and identifies critical SEO issues in under 10 seconds." },
      { label: "Lead scoring", desc: "Automatically scores leads 0-100 based on how many issues their site has. More issues = higher score = bigger opportunity." },
      { label: "Email capture", desc: "Once issues are shown, prospects enter their email to get the full report — converting curiosity into a lead." },
    ],
    tips: [
      "High lead scores (70+) mean the site has many issues — these are your best prospects.",
      "The audit checks 4 basic things. A full audit via /playground checks 47 points.",
      "Add the /intake URL to your email signature, LinkedIn, and anywhere you market.",
      "After a lead comes in, go to /empire and click get_prospects to see all leads, then generate_proposal for the hot ones.",
    ],
    faq: [
      { q: "What does the lead score mean?", a: "85+ = critical issues, high urgency. 60-85 = multiple problems, strong opportunity. Below 60 = site is decent, pitch differentiation instead of fixes." },
      { q: "Does the prospect see all their issues?", a: "They see the top-level issues (missing tags, no schema). The full 47-point audit is generated separately and requires a proper client setup." },
      { q: "How do I follow up with a lead?", a: "Go to /empire or use get_prospects action. The lead has their URL, email, score, and audit data. Use generate_proposal to create a custom HTML proposal." },
    ],
  },

  "morning-brief": {
    title: "Morning Brief — Daily AI Intelligence",
    what: "Every morning, the AI analyses your entire empire and creates a prioritised briefing. What happened, what to do, what to watch.",
    why: "Instead of checking 10 different tools, the Morning Brief synthesises everything: recent learnings, verification results, pending alerts, algorithm signals. It tells you the 3 most important things to act on today and why. Generated fresh every morning by the daily 6am automation.",
    howTo: [
      { step: "Open first thing in the morning", detail: "The brief is generated automatically at 6am UTC by the daily cron. Open /morning-brief and today's brief is already there." },
      { step: "Read the headline", detail: "One sentence that captures the empire's status. If something is wrong, it's in the headline." },
      { step: "Action the priority list", detail: "3 items ranked HIGH/MEDIUM/LOW. Each has what to do and why. Do the HIGH ones first." },
      { step: "Check wins and risks", detail: "Wins = what worked yesterday, reinforce these. Risks = what needs attention before it becomes a problem." },
      { step: "Regenerate if stale", detail: "If the brief looks old or generic, click Regenerate to get a fresh AI analysis of current data." },
    ],
    actions: [
      { label: "Priority Actions", desc: "3 AI-ranked actions for today with impact level (HIGH/MEDIUM/LOW) and reasoning." },
      { label: "Yesterday's Wins", desc: "Verified tactics that are working — reinforce these in your work today." },
      { label: "Risks to Address", desc: "Problems building up that need attention before they become critical." },
      { label: "Opportunities", desc: "Things spotted by AI that could deliver wins if acted on." },
      { label: "Algorithm Watch", desc: "Any Google algorithm signals that might affect client rankings." },
    ],
    tips: [
      "The brief uses data from the last 24 hours of verifications and the last 7 days of learnings.",
      "If priority actions look generic, it means the Brain doesn't have enough data yet. Run more tasks and verifications.",
      "Regenerate refreshes the analysis with the very latest data — useful if something changed overnight.",
      "Share the brief with your team — it replaces a morning standup for SEO status.",
    ],
    faq: [
      { q: "When is the brief generated automatically?", a: "At 6am UTC every day via the Vercel cron job. If you need it earlier, click Regenerate." },
      { q: "Why does the brief say 'building...' for wins?", a: "No verifications have been completed yet. Go to /brain-command and run some task verifications to build the wins library." },
      { q: "Can I get a brief for a specific project?", a: "Yes — the brief engine supports project-scoped briefs. Use the API action generate_morning_brief with a projectId." },
    ],
  },

  "llm-visibility": {
    title: "LLM Visibility — AI Citation Tracker",
    what: "Track whether AI models like ChatGPT, Claude, and Gemini mention and recommend your clients when users ask relevant questions.",
    why: "40% of searches now go to AI instead of Google. If your client isn't being cited by AI models, they're invisible to a growing audience. This page tests visibility by asking Claude questions a real user would ask, and checking if your client is mentioned positively, neutrally, or not at all.",
    howTo: [
      { step: "Select a project", detail: "Choose which client to check from the dropdown. Each check uses their industry, market, and goals to form realistic queries." },
      { step: "Click Run Check", detail: "The system asks Claude 3 questions: best companies in their industry, who to use for their service, and about them directly." },
      { step: "Read the results", detail: "Green ✅ = cited. Red ❌ = not mentioned. Each gap comes with a specific improvement hint." },
      { step: "Act on the gaps", detail: "Not cited for 'best X companies'? Create authoritative content on that topic. The improvement hint tells you exactly what to do." },
      { step: "Track over time", detail: "Run checks weekly. Watch the citation rate improve as you create LLM-optimised content." },
    ],
    actions: [
      { label: "Citation Rate", desc: "% of queries where the client is mentioned. Target: above 60%. Below 30% is an urgent problem." },
      { label: "Positive Mentions", desc: "Queries where the AI recommends the client. This is the highest-value outcome." },
      { label: "Gaps Found", desc: "Queries where the client wasn't mentioned. Each gap is a content opportunity." },
      { label: "Run Check", desc: "Triggers a fresh visibility check using the latest AI model. Takes 15-30 seconds." },
    ],
    tips: [
      "LLM visibility improves fastest by creating direct-answer content — pages that answer the exact query concisely.",
      "Structured data (schema markup) helps AI models understand and cite your content.",
      "Being cited positively ('best', 'recommended', 'leading') is worth 3x being cited neutrally.",
      "Check competitors too — if they're being cited and your client isn't, analyse their content structure.",
      "New clients often start at 0% — this is normal. 3 months of LLM-optimised content typically gets to 40-60%.",
    ],
    faq: [
      { q: "Why is citation rate 0% for a new client?", a: "New clients haven't built authority with AI models yet. AI cites what it knows from training data. Content strategy focused on LLM optimisation takes 2-3 months to show results." },
      { q: "Does this only check Claude?", a: "Currently uses Claude Haiku as the test model. It's a strong proxy for LLM visibility generally — content visible to Claude tends to be visible to other AI models too." },
      { q: "How often should I run checks?", a: "Weekly is ideal. Run after publishing new content to see if it improved visibility. Monthly is the minimum." },
    ],
  },

  health: {
    title: "Client Health — Churn Prevention & Upsell Detection",
    what: "Automatic health scores for every client, updated daily. Predicts churn before it happens and spots upsell opportunities.",
    why: "Losing a client costs 5-7x more than keeping one. This page shows each client's health score (0-100) based on task velocity, brain learnings, and verification results. Churn risk is flagged early so you can act before the client is unhappy. Upsell signals surface clients ready to expand.",
    howTo: [
      { step: "Review scores daily", detail: "Open /health each morning. Red border = high churn risk, needs a call or re-engagement. Green = healthy, potentially ready for upsell." },
      { step: "Understand the score", detail: "Score = (Brain Score × 0.5) + (Velocity Score × 0.5). Brain = how much the AI is learning. Velocity = how many tasks are getting done." },
      { step: "Act on churn signals", detail: "Each high-risk client shows the specific signals. 'No tasks completed in 30 days' means execution has stalled — restart the task engine." },
      { step: "Convert upsell signals", detail: "Green scores with '💡 Upsell opportunity' mean results are strong — schedule an expansion conversation." },
      { step: "Recalculate to refresh", detail: "Click Recalculate All to refresh all scores with the latest data. Runs automatically daily at 6am." },
    ],
    actions: [
      { label: "Overall Score (0-100)", desc: "Combined health indicator. 70+ = healthy. 50-70 = watch closely. Below 50 = intervention needed." },
      { label: "Brain Score", desc: "How much the AI system is learning from this client's work. Low = not enough tasks or verifications running." },
      { label: "Velocity Score", desc: "Task completion rate in the last 30 days. Low = work has stalled. High = strong execution." },
      { label: "Churn Risk", desc: "LOW/MEDIUM/HIGH/CRITICAL based on signals. Critical triggers an automatic alert." },
      { label: "Upsell Signals", desc: "Appears when results are strong and the client is ready for expansion services." },
    ],
    tips: [
      "A client with high velocity but low brain score is doing work but not learning — add verifications.",
      "Renewal date tracking: clients with < 30 days to renewal show a countdown. Prepare renewal conversations early.",
      "The 'No learnings captured recently' signal means the AI isn't extracting insights. Check ai-cache.ts is working.",
      "Health scores update automatically daily but you can force a refresh anytime with Recalculate All.",
    ],
    faq: [
      { q: "Why is a client at 0 health?", a: "Usually means no task_executions in the last 30 days AND no brain_learnings. The client's work has completely stalled. Check what's blocking tasks in /brain-command." },
      { q: "How is the renewal date calculated?", a: "Estimated from project creation date, calculating the next 6-month milestone. Not from an actual contract — you can update it in the project settings." },
      { q: "What triggers a critical churn alert?", a: "Two or more signals: no tasks completed AND no learnings captured. This creates an automatic alert in /alerts." },
    ],
  },

  alerts: {
    title: "Alert Center — Smart Notifications",
    what: "Every important event in the empire surfaces here automatically. Ranking drops, LLM visibility losses, churn risks, algorithm changes.",
    why: "You can't monitor everything manually. The alert system watches for you — ranking changes, client health deterioration, LLM citations lost, algorithm updates, renewal dates approaching. Urgent items appear in red and trigger badges on Empire Command.",
    howTo: [
      { step: "Check alerts daily", detail: "Filter by 'Unread' to see only new alerts. Dismiss what you've actioned to keep the feed clean." },
      { step: "Prioritise by severity", detail: "URGENT = act now. CRITICAL = act today. WARNING = act this week. INFO = awareness only." },
      { step: "Filter by type", detail: "Use the filter buttons to see only churn risks, ranking changes, LLM issues, or algorithm updates." },
      { step: "Click to dismiss", detail: "Tap any alert to mark it as read. Use Dismiss All to clear all read alerts at once." },
    ],
    actions: [
      { label: "algorithm_change", desc: "Google algorithm update detected. Check which clients are in affected industries." },
      { label: "ranking_drop", desc: "A keyword dropped more than 5 positions. Investigate content changes or technical issues." },
      { label: "ranking_rise", desc: "A keyword gained more than 5 positions. Identify what worked and replicate it." },
      { label: "churn_risk", desc: "Client health score has deteriorated. High = needs a call this week. Critical = call today." },
      { label: "llm_mention_lost", desc: "Client was not cited by AI for a relevant query. Create targeted content for that query." },
      { label: "renewal_due", desc: "Client contract approaching renewal date. Prepare results summary and renewal proposal." },
    ],
    tips: [
      "Set a habit: check alerts every morning before starting work. 2 minutes of triage prevents bigger problems.",
      "Ranking drops often correlate with algorithm changes — cross-reference with the algorithm_change alerts.",
      "llm_mention_lost alerts are content opportunities — each one tells you exactly what to write.",
      "Don't dismiss alerts without actioning them — they're your quality control system.",
    ],
    faq: [
      { q: "How are alerts generated?", a: "Automatically by the system: health engine creates churn_risk alerts, LLM probe creates llm_mention_lost alerts, ranking velocity creates ranking_drop/rise alerts. No manual configuration needed." },
      { q: "Why do I have no alerts?", a: "Alerts are generated as automations run. If health scores haven't been calculated and LLM checks haven't run, there's nothing to alert on. Run calculate_all_health and check_llm_visibility to start." },
    ],
  },

  reports: {
    title: "Reports — Automated Client Reporting",
    what: "Generate beautiful, professional SEO reports with one click. Weekly, monthly, and quarterly. Client-ready HTML delivered instantly.",
    why: "Manual reporting wastes hours every week. This page generates AI-written reports using real data from the system — tasks completed, learnings captured, verified wins, metrics. The output is client-ready HTML you can share directly or copy into any format.",
    howTo: [
      { step: "Select a client", detail: "Choose the project from the dropdown. The report will use all data associated with that project." },
      { step: "Choose report type", detail: "Weekly = last 7 days. Monthly = last 30 days. Quarterly = last 90 days. Match your client reporting cadence." },
      { step: "Click Generate", detail: "Takes 15-30 seconds. The AI writes a professional report using actual task data, learnings, and verified wins." },
      { step: "Preview and share", detail: "Preview appears inline. Click View ↗ to open the shareable URL. Send the link directly to clients." },
      { step: "Set up weekly automation", detail: "The daily cron generates weekly reports every Monday automatically. You just need to review and send." },
    ],
    actions: [
      { label: "Weekly Report", desc: "Last 7 days of activity. Tasks completed, wins achieved, what was learned, next week's plan." },
      { label: "Monthly Report", desc: "30-day overview. Best for most client reporting cadences." },
      { label: "Quarterly Report", desc: "90-day strategic view. Shows trajectory and compound progress." },
      { label: "Shareable Link", desc: "Each report gets a unique token-based URL. Share directly with clients — no login required." },
    ],
    tips: [
      "Reports are better when the Brain has more data — run verifications regularly to build the wins library.",
      "The report uses actual numbers: tasks done, learnings count, verified wins list. More activity = better report.",
      "Monday morning reports are auto-generated by the cron. Check the Reports page Monday morning and they're ready.",
      "Client can bookmark their report URL — it always shows the latest report generated for them.",
    ],
    faq: [
      { q: "Why does the report say 'building' for wins?", a: "No verification_queue entries have been completed yet. Run some tasks and verifications through /brain-command to build the wins library." },
      { q: "Can I customise the report style?", a: "The report uses dark-themed HTML with your brand colours. To customise, modify the prompt in api/lib/report-engine.ts." },
      { q: "Are reports auto-sent to clients?", a: "Not yet — generation is automatic but sending requires your action. Future roadmap includes email delivery." },
    ],
  },

  "content-hub": {
    title: "Content Hub — LLM-Optimised Content Briefs",
    what: "Generate comprehensive content briefs for any keyword, optimised for both Google rankings and AI citation.",
    why: "Most content briefs just cover keyword density. These briefs go further — they include the direct answer AI models need to cite the content, entity coverage for knowledge graph optimisation, competitor gaps to exploit, and a structured outline that satisfies search intent. Writers know exactly what to produce.",
    howTo: [
      { step: "Select a project", detail: "The brief will be tailored to the client's industry, market, and existing strategy." },
      { step: "Enter a target keyword", detail: "Type the primary keyword or topic. Be specific — 'best accounting software for freelancers' is better than 'accounting software'." },
      { step: "Click Generate Brief", detail: "Takes 10-20 seconds. AI analyses the keyword, client context, and competitor gaps to produce a complete brief." },
      { step: "Read the LLM Direct Answer", detail: "The green box shows the exact answer to put at the top of the article — this is what makes AI models cite the content." },
      { step: "Pass to your writer", detail: "The brief includes title, word count, structure, entities to cover, and specific guidance. Writers can produce the content without any further briefing." },
    ],
    actions: [
      { label: "Brief Generation", desc: "Complete content brief with title, secondary keywords, intent classification, structure, and word count." },
      { label: "LLM Direct Answer", desc: "The specific answer to put at the article's top. Engineered to trigger AI model citations." },
      { label: "Entity Coverage", desc: "List of entities (people, organisations, concepts) to mention for knowledge graph signals." },
      { label: "Unique Angle", desc: "What makes this piece different from competitor content — your differentiation point." },
    ],
    tips: [
      "The LLM Direct Answer is the most valuable part — always include it verbatim at the top of the article.",
      "Entity coverage improves with each brief — the system learns which entities matter for each client.",
      "High priority briefs are for keywords with immediate business impact. Generate these first.",
      "Pair content briefs with the competitor analysis — brief the gaps competitors haven't covered well.",
    ],
    faq: [
      { q: "What is 'search intent' and why does it matter?", a: "Informational = user wants to learn. Transactional = user wants to buy. Navigational = user wants to find a specific page. Matching intent is crucial — Google and AI models both penalise mismatched content." },
      { q: "How many briefs should I generate per client per month?", a: "4-8 briefs per month is typical for active clients. Each brief should result in one published piece. Quality over quantity." },
    ],
  },

  "brain-command": {
    title: "Brain Command — Intelligence Dashboard",
    what: "The SEO Brain is the learning engine. Every task executed, every result verified, every pattern identified — stored here and used to improve future work.",
    why: "Traditional SEO agencies do the same thing repeatedly and hope for different results. The Brain remembers what worked and what didn't across every client and every project. Over time, it builds compound intelligence — making every new task smarter than the last.",
    howTo: [
      { step: "Check learning velocity", detail: "The chart shows learnings captured over time. Flat = Brain isn't being fed. Steep = system learning fast." },
      { step: "Review recent learnings", detail: "Each learning card shows what worked, what was missed, confidence score, and how many times applied." },
      { step: "Look at project health grid", detail: "Colour-coded grid showing which projects are healthy (green) vs struggling (red). Drill into red projects." },
      { step: "Use the algorithm radar", detail: "Shows which algorithm factors the Brain has learned about. Bigger shape = more knowledge in that area." },
    ],
    actions: [
      { label: "Learning Velocity Chart", desc: "How fast the Brain is capturing new learnings. Target: 3+ new learnings per week per active project." },
      { label: "Project Health Grid", desc: "Visual overview of all project health statuses." },
      { label: "Algorithm Radar", desc: "Coverage map of algorithm knowledge areas." },
      { label: "Recent Learnings", desc: "Newest entries in the Brain with confidence scores and application counts." },
    ],
    tips: [
      "The Brain learns from verifications — if you don't verify task outcomes, the Brain doesn't learn.",
      "High confidence scores (80+) mean a tactic has been proven multiple times. These are your most valuable playbooks.",
      "Cross-project learning is the moat — a tactic proven for one client benefits all similar clients automatically.",
      "Click any learning card to see full detail: what worked, what missed, redo reason, and improvement.",
    ],
    faq: [
      { q: "How does the Brain learn?", a: "Every API call that generates content runs extractAndSaveLearning() automatically. The AI analyses the result and extracts structured learnings — what worked, what missed, and how to improve." },
      { q: "What's a good Brain score?", a: "New projects start at 0. After 1 month of active work: 20-40 learnings. After 3 months: 100+. High-quality learnings matter more than quantity." },
    ],
  },


  "client-dashboard": {
    title: "Client Dashboard — Your Campaign View",
    what: "Your personal window into your SEO campaign. Real metrics, real progress, no agency jargon.",
    why: "Everything you need to understand what's happening with your SEO, presented clearly. Traffic growth, rankings, AI visibility, verified wins — all in one place, updated daily.",
    howTo: [
      { step: "Check your headline metric", detail: "The traffic number at the top is your most important weekly number — organic visits from search engines." },
      { step: "Read this week's focus", detail: "The priority actions tell you what your team is working on and why it matters for your goals." },
      { step: "Review wins", detail: "Verified wins are tactics we've confirmed are working. These compound — each win makes the next one more powerful." },
      { step: "Check notifications", detail: "Alerts tell you about important changes — ranking improvements, issues found, opportunities spotted." },
      { step: "View reports", detail: "Monthly reports give you the full picture with all data and explanations." },
    ],
    actions: [
      { label: "Traffic Metrics", desc: "Monthly organic visits — the core measure of SEO success." },
      { label: "AI Visibility Score", desc: "How often AI models like ChatGPT and Claude mention and recommend you." },
      { label: "Verified Wins", desc: "Tactics we tested and confirmed are working on your specific site." },
    ],
    tips: [
      "LLM visibility is the new frontier — if AI doesn't mention you, you're invisible to 40% of searches.",
      "Organic traffic compounds — early months are slower, months 4-6 accelerate.",
      "Each win builds on the last. The Brain system learns what works for your industry.",
    ],
    faq: [
      { q: "Why does traffic look low in month 1?", a: "SEO takes 2-4 months to build momentum. Think of it as building a foundation — slow start, then compound growth." },
      { q: "What is AI visibility?", a: "When someone asks ChatGPT or Claude for recommendations in your industry, are you mentioned? This tracks that." },
    ],
  },

  "content-writer": {
    title: "Content Intelligence — Writer Dashboard",
    what: "Your command centre for creating content that ranks on Google AND gets cited by AI models.",
    why: "Modern SEO content must satisfy both search engines and AI systems. This dashboard gives you structured briefs, LLM optimisation tips, entity lists, and a content calendar — everything you need to write content that actually performs.",
    howTo: [
      { step: "Check your brief queue", detail: "High priority briefs need content first. Look for red and amber priority indicators." },
      { step: "Read the full brief", detail: "Click any brief to expand it. The brief content tells you everything to cover." },
      { step: "Copy the LLM direct answer", detail: "The green LLM box is the most important. Put this exact answer at the TOP of your article." },
      { step: "Cover all entities", detail: "The entity list shows what people, companies, and concepts to mention in your article." },
      { step: "Check the calendar", detail: "Publishing schedule shows what to write and when." },
    ],
    actions: [
      { label: "Generate Brief", desc: "Enter any keyword to get a complete writing brief in 15 seconds." },
      { label: "LLM Direct Answer", desc: "The specific answer to put at the top of your article to trigger AI citations." },
      { label: "Content Calendar", desc: "4-week publishing schedule generated from keyword priorities." },
    ],
    tips: [
      "The LLM Direct Answer is worth more than any other part of the brief. Always use it verbatim at the top.",
      "Entity coverage is what builds topical authority — mention all listed entities naturally in the article.",
      "High priority briefs target keywords with the fastest path to ranking. Do those first.",
    ],
    faq: [
      { q: "How long should articles be?", a: "Follow the word count in each brief — it's calculated from what the top-ranking competitors are doing for that specific keyword." },
      { q: "Should I write for AI or for humans?", a: "Write for humans first — clear, direct, genuinely helpful. AI citation follows automatically when you put the direct answer first and cover entities properly." },
    ],
  },
};
