import React,{useState,useEffect} from "react";
import PortalNav from "@/components/PortalNav";
import {useProject} from "@/contexts/ProjectContext";
const post=(a:string,b:any={})=>fetch("/api/task-engine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:a,...b})}).then(r=>r.json()).catch(()=>({}));
export default function ClientComms(){
  const{selectedProjectId:projectId}=useProject();
  const[tab,setTab]=useState<"analyse"|"history">("analyse");
  const[conv,setConv]=useState("");
  const[analysis,setAnalysis]=useState<any>(null);
  const[busy,setBusy]=useState(false);
  const[history,setHistory]=useState<any[]>([]);
  useEffect(()=>{post("get_client_conversations",{projectId,limit:10}).then(r=>setHistory((r as any).conversations||[]));},[projectId]);
  const analyse=async()=>{ if(!conv.trim())return; setBusy(true); const r=await post("analyse_fiverr_conversation",{conversation:conv,projectId}); setAnalysis(r); setBusy(false); };
  return(<div className="min-h-screen bg-background text-foreground"><PortalNav/><div className="max-w-5xl mx-auto px-6 py-8"><div className="mb-6"><h1 className="text-2xl font-bold">Client Comms</h1><p className="text-sm text-muted-foreground mt-1">AI conversation analyser</p></div><div className="flex gap-1 mb-6 border-b border-border">{(["analyse","history"] as const).map(t=>(<button key={t} onClick={()=>setTab(t)} className={`px-4 py-2 text-sm font-medium capitalize border-b-2 -mb-px ${tab===t?"border-primary text-primary":"border-transparent text-muted-foreground hover:text-foreground"}`}>{t}</button>))}</div>{tab==="analyse"&&<div className="space-y-4"><textarea value={conv} onChange={e=>setConv(e.target.value)} rows={7} placeholder="Paste conversation..." className="w-full rounded-xl border border-border bg-card px-4 py-3 text-sm outline-none resize-none"/><button onClick={analyse} disabled={busy||!conv.trim()} className="px-6 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-medium disabled:opacity-50">{busy?"Analysing...":"Analyse"}</button>{analysis&&<div className="rounded-2xl border border-border bg-card p-5 space-y-3">{analysis.sentiment&&<div><div className="text-xs text-muted-foreground uppercase tracking-widest mb-1">Sentiment</div><div className="text-sm capitalize">{analysis.sentiment}</div></div>}{analysis.summary&&<div><div className="text-xs text-muted-foreground uppercase tracking-widest mb-1">Summary</div><div className="text-sm">{analysis.summary}</div></div>}{analysis.suggested_responses?.map((r:string,i:number)=>(<div key={i} className="flex gap-2 p-3 rounded-xl bg-secondary/50"><div className="flex-1 text-sm">{r}</div><button onClick={()=>navigator.clipboard.writeText(r)} className="text-xs text-primary flex-shrink-0">Copy</button></div>))}</div>}</div>}{tab==="history"&&<div className="space-y-3">{history.map((h:any,i:number)=>(<div key={h.id||i} className="rounded-2xl border border-border bg-card p-4"><div className="flex justify-between items-start mb-1"><div className="text-sm font-medium">{h.title||`Conv ${i+1}`}</div><div className="text-xs text-muted-foreground">{h.created_at?.slice(0,10)}</div></div>{h.summary&&<div className="text-xs text-muted-foreground">{h.summary}</div>}</div>))}{!history.length&&<div className="text-center py-12 text-sm text-muted-foreground">No history.</div>}</div>}</div></div>);
}
