import React,{useState,useEffect} from "react";
import PortalNav from "@/components/PortalNav";
import {useProject} from "@/contexts/ProjectContext";
const post=(a:string,b:any={})=>fetch("/api/task-engine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:a,...b})}).then(r=>r.json()).catch(()=>({}));
export default function ClientDashboard(){
  const{selectedProjectId:projectId,selectedProject}=useProject();
  const[metrics,setMetrics]=useState<any>({});
  const[health,setHealth]=useState<any>(null);
  const[learnings,setLearnings]=useState<any[]>([]);
  const[loading,setLoading]=useState(true);
  useEffect(()=>{ if(!projectId)return; Promise.all([post("get_project_metrics",{projectId}),post("get_client_health",{projectId}),post("get_brain_learnings",{projectId,limit:5})]).then(([m,h,l])=>{setMetrics((m as any).metrics||m);setHealth((h as any).health||h);setLearnings((l as any).learnings||[]);setLoading(false);}); },[projectId]);
  return(<div className="min-h-screen bg-background text-foreground"><PortalNav/><div className="max-w-5xl mx-auto px-6 py-8"><div className="mb-6"><h1 className="text-2xl font-bold">{selectedProject?.name||"Client Dashboard"}</h1><p className="text-sm text-muted-foreground mt-1">{selectedProject?.url||"Campaign performance"}</p></div>{loading?<div className="text-center py-16 text-sm text-muted-foreground">Loading...</div>:<div className="space-y-4"><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[{v:metrics.organic_traffic||0,l:"Traffic",c:"#10b981"},{v:metrics.organic_keywords||0,l:"Keywords",c:"#6366f1"},{v:metrics.top_10_keywords||0,l:"Top 10",c:"#06b6d4"},{v:metrics.llm_visibility_score||0,l:"LLM %",c:"#f59e0b"}].map(s=>(<div key={s.l} className="rounded-2xl border border-border bg-card p-4"><div className="text-xs text-muted-foreground mb-1">{s.l}</div><div className="text-2xl font-bold font-mono" style={{color:s.c}}>{s.v.toLocaleString()}</div></div>))}</div>{health&&<div className="rounded-2xl border border-border bg-card p-5"><div className="text-xs font-bold text-muted-foreground uppercase tracking-widest mb-3">Health</div><div className="flex items-center gap-4"><div className="text-4xl font-bold font-mono text-primary">{health.overall_score||0}</div><div><div className="text-sm font-medium capitalize">{health.churn_risk||"low"} risk</div><div className="text-xs text-muted-foreground mt-0.5">{health.recommended_action}</div></div></div></div>}{learnings.length>0&&<div className="rounded-2xl border border-border bg-card p-5"><div className="text-xs font-bold text-muted-foreground uppercase tracking-widest mb-3">Wins</div>{learnings.map((l:any,i:number)=>(<div key={i} className="flex items-center gap-3 py-2 border-b border-border/50 last:border-0"><div className="h-5 w-5 rounded-full bg-green-500/10 flex items-center justify-center text-xs text-green-400">✓</div><div className="flex-1 text-sm">{l.card_title}</div><div className="text-xs font-mono text-primary">{l.confidence_score}%</div></div>))}</div>}</div>}</div></div>);
}
