import React from "react";
import PortalNav from "@/components/PortalNav";
import {useTheme} from "@/contexts/ThemeContext";
import {THEMES,type ThemeId} from "@/lib/theme-engine";
const LIST=[{id:"void",name:"Void",icon:"🌌",desc:"Deep space teal",moods:["Precise","Technical"]},{id:"obsidian",name:"Obsidian",icon:"💎",desc:"Electric violet",moods:["Premium","Dark"]},{id:"arctic",name:"Arctic",icon:"❄️",desc:"Ice precision",moods:["Clean","Sharp"]},{id:"carbon",name:"Carbon",icon:"🔩",desc:"Industrial amber",moods:["Heavy","Bold"]},{id:"emerald",name:"Emerald",icon:"🌿",desc:"Forest organic",moods:["Calm","Growth"]},{id:"rose",name:"Rose",icon:"🌹",desc:"Fashion editorial",moods:["Elegant","Refined"]},{id:"solar",name:"Solar",icon:"☀️",desc:"Desert gold",moods:["Luxury","Warm"]},{id:"matrix",name:"Matrix",icon:"🖥",desc:"Terminal green",moods:["Focused","Sharp"]},{id:"vapor",name:"Vapor",icon:"🌊",desc:"Retrowave",moods:["Creative","Retro"]},{id:"cobalt",name:"Cobalt",icon:"🔷",desc:"Enterprise blue",moods:["Deep","Solid"]}];
export default function ThemePreview(){
  const{themeId,mode,setThemeId,toggle}=useTheme();
  return(<div className="min-h-screen bg-background text-foreground"><PortalNav/><div className="max-w-4xl mx-auto px-6 py-8"><div className="text-center mb-8"><h1 className="text-3xl font-bold mb-2">Choose Your World</h1><p className="text-sm text-muted-foreground mb-4">10 environments.</p><div className="flex items-center justify-center gap-2"><span className="text-xs text-muted-foreground">Night</span><button onClick={toggle} className="relative w-10 h-5 rounded-full" style={{background:mode==="light"?"hsl(var(--primary))":"hsl(var(--muted))"}}><div className="absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-all" style={{left:mode==="light"?"22px":"2px"}}></div></button><span className="text-xs text-muted-foreground">Day</span></div></div><div className="grid gap-3" style={{gridTemplateColumns:"repeat(auto-fill,minmax(175px,1fr))"}}>{LIST.map(t=>{ const td=(THEMES as any)[`${t.id}_${mode}`]; const active=themeId===t.id; return(<button key={t.id} onClick={()=>setThemeId(t.id as ThemeId)} className={`text-left p-4 rounded-2xl border transition-all ${active?"border-primary bg-primary/5":"border-border bg-card hover:border-primary/40"}`}><div className="flex gap-2 mb-3 items-center"><span className="text-2xl">{t.icon}</span><div className="flex flex-col gap-0.5">{td&&[td.accent,td.accentAlt,td.accentSoft].map((c:string,j:number)=>(<div key={j} className="h-1 w-8 rounded-full" style={{background:c}}></div>))}</div></div><div className="font-semibold text-sm mb-1">{t.name}</div><div className="text-xs text-muted-foreground mb-2">{t.desc}</div><div className="flex flex-wrap gap-1">{t.moods.map(m=>(<span key={m} className="text-[9px] px-1.5 py-0.5 rounded bg-primary/10 text-primary">{m}</span>))}</div>{active&&<div className="mt-2 text-[10px] font-bold text-primary">ACTIVE</div>}</button>); })}</div></div></div>);
}
